alumni_support_system/urls.py
"""
Definition of urls for alumni_support_system.
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf.urls import include, url
from django.contrib.auth import views
from core import views as core_views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', alumni_support_system.views.home, name='home'),
    # url(r'^alumni_support_system/', include('alumni_support_system.alumni_support_system.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^$', core_views.home, name = 'home'),
    url(r'^login/$', views.login),
    url(r'^logout/$', views.logout, {'next_page' : '/login'}),
    url(r'^login/register/$', core_views.register_page),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^profile/$', core_views.view_profile, name = 'view_profile'),
    url(r'^profile/editprofile/$', core_views.update_profile, name='edit_profile'),
    url(r'^profile/writetestimonial/$', core_views.write_testimonial, name='write_testimonial'),
    url(r'^profile/viewtestimonial/$', core_views.view_testimonial, name='view_testimonial'),
    url(r'^profile/deletetestimonial/$', core_views.delete_testimonial, name='delete_testimonial'),
    url(r'^settings/$', core_views.settings, name='settings'), 
    url(r'^settings/changepassword/$', core_views.change_password, name='change_password'),
    url(r'^settings/deleteuser/$', core_views.delete_user, name='delete_user'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT})

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
     

core/urls.py
"""
Definition of urls for alumni_support_system.
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf.urls import include, url
from django.contrib.auth import views
from core import views as core_views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', alumni_support_system.views.home, name='home'),
    # url(r'^alumni_support_system/', include('alumni_support_system.alumni_support_system.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^$', core_views.home, name = 'home'),
    url(r'^login/$', views.login),
    url(r'^logout/$', views.logout, {'next_page' : '/login'}),
    url(r'^login/register/$', core_views.register_page),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    
    url(r'^profile/$', core_views.view_profile, name = 'view_profile'),
    url(r'^profile/editprofile/$', core_views.update_profile, name='edit_profile'),
    url(r'^profile/writetestimonial/$', core_views.write_testimonial, name='write_testimonial'),
    url(r'^profile/viewtestimonial/$', core_views.view_testimonial, name='view_testimonial'),
    url(r'^profile/deletetestimonial/$', core_views.delete_testimonial, name='delete_testimonial'),
    
    url(r'^settings/$', core_views.settings, name='settings'), 
    url(r'^settings/changepassword/$', core_views.change_password, name='change_password'),
    url(r'^settings/deleteuser/$', core_views.delete_user, name='delete_user'),
    
    url(r'^questionanswer/$', core_views.question_answer, name='question_answer_home'),
    url(r'^questionasnwer/askquestion/$', core_views.post_question, name='post_question'),
    url(r'^questionanswer/answerquestion/(?P<pk>\d+)/$', core_views.post_answer, name='post_answer'),
    url(r'^questionanswer/viewanswers/(?P<pk>\d+)/$', core_views.view_answer, name='view_answer'),
    url(r'^questionanswer/viewaskedquestions/$', core_views.view_asked_question, name='view_asked_question'),
    url(r'^questionanswer/viewaskedquestions/viewanswers/(?P<pk>\d+)/$', core_views.view_answer, name='view_answer2'),
    url(r'^questionanswer/viewansweredquestions/$', core_views.view_answered_question, name='view_answered_question'),
    url(r'^questionanswer/viewansweredquestions/viewanswers/(?P<pk>\d+)/$', core_views.view_answer, name='view_answer3'),
    url(r'^questionanswer/viewunansweredquestions/$', core_views.view_unanswered_question, name = 'view_unanswered_question'),
    url(r'^questionanswer/viewaskedquestions/deletequestion/(?P<pk2>\d+)/$', core_views.delete_question, name = 'delete_question'),
    #url(r'^questionanswer/viewanswers/(?P<pk>\d+)/deleteanswer/(?P<pk2>\d+)/$', core_views.delete_answer, name='delete_answer'),
    #url(r'^questionanswer/viewaskedquestions/viewanswers/(?P<pk>\d+)/deleteanswer/(?P<pk2>\d+)/$', core_views.delete_answer, name='delete_answer'),
    #url(r'^questionanswer/viewansweredquestions/viewanswers/(?P<pk>\d+)/deleteanswer/(?P<pk2>\d+)/$', core_views.delete_answer, name='delete_answer'),

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT})

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
     

core/models.py
import os
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import datetime,date


# Create your models here.

#NOTE : delete all users from admin before making any changes to model

#to save user dp in media/users/user_id/filename
def get_image_path(instance, filename):
    return os.path.join('users', str(instance.id), filename)

#dummy just ignore
def get_event_image_path(instance, filename):
    return os.path.join('events', str(instance.id), filename)


class Profile(models.Model):
    
    BATCH_CHOICES = (
        ('NA', 'Not Applicable'),
        ('1998','1998'),
        ('1999','1999'),
        ('2000','2000'),
        ('2001','2001'),
        ('2002','2002'),
        ('2003','2003'),
        ('2004','2004'),
        ('2005','2005'),
        ('2006','2006'),
        ('2007','2007'),
        ('2008','2008'),
        ('2009','2009'),
        ('2010','2010'),
        ('2011','2011'),
        ('2012','2012'),
        ('2013','2013'),
        ('2014','2014'),
        ('2015','2015'),
        ('2016','2016'),
        )

    
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        )

    
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    pic = models.ImageField(upload_to=get_image_path, default = os.path.join('users', 'default_avatar.jpg'))
    bio = models.TextField(max_length=500, default = '', blank=True)
    gender = models.CharField(max_length=1, choices = GENDER_CHOICES, blank = True)
    city = models.CharField(max_length=30,default = '', blank=True)
    batch = models.CharField(max_length=4, choices = BATCH_CHOICES, blank=True)
    website = models.URLField(default='', blank=True)
    twitter = models.URLField(default='', blank=True)
    linkedin = models.URLField(default='', blank=True)
    organization = models.CharField(max_length=100, default='', blank=True)

#so that profile is created and saved each time a user is created
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Testimonial(models.Model):
    user = models.OneToOneField(User, null = True, on_delete = models.CASCADE)
    content = models.TextField(max_length = 1000, default = '', blank =  True)
    pub_date = models.DateTimeField(auto_now_add = True)


class Question(models.Model):
    user = models.ForeignKey(User, null = True, on_delete = models.CASCADE)
    title = models.TextField(max_length = 200)
    description = models.TextField(max_length = 500, default = '', blank = True)
    pub_date = models.DateTimeField(auto_now_add = True)


class Answer(models.Model):
    user = models.ForeignKey(User, null = True, on_delete = models.CASCADE)
    question = models.ForeignKey(Question, null = True, on_delete = models.CASCADE)
    answer = models.TextField(max_length = 1000)
    pub_date = models.DateTimeField(auto_now_add = True)
 

class Event(models.Model):
    user = models.ForeignKey(User, null = True, on_delete = models.CASCADE)
    title = models.TextField(max_length = 50)
    date = models.DateField(default = date.today)
    time = models.TimeField(default = datetime.now)
    venue = models.TextField(max_length = 50)
    description = models.TextField(max_length = 500, blank = True, default = '')
    icon = models.ImageField(upload_to=get_image_path, default = os.path.join('users', 'default_icon.jpg'))
    pub_date = models.DateTimeField(auto_now_add = True)
 

class EventAttendees(models.Model):
    user = models.ForeignKey(User, null = True, on_delete = models.CASCADE)
    event = models.ForeignKey(Event, null = True, on_delete = models.CASCADE)


class EventGallery(models.Model):
    user = models.ForeignKey(User, null = True, on_delete = models.CASCADE)
    event = models.ForeignKey(Event, null = True, on_delete = models.CASCADE)
    pic = models.ImageField(upload_to = get_image_path, blank = True, null = True)
    pub_date = models.DateTimeField(auto_now_add = True)


class Comment(models.Model):
    user = models.ForeignKey(User, null = True, on_delete = models.CASCADE)
    event = models.ForeignKey(Event, null = True, on_delete = models.CASCADE)
    content = models.TextField(max_length = 200)
    pub_date = models.DateTimeField(auto_now_add = True)
   

core/forms.py
import re
from django.contrib.auth.models import User, Group
from core.models import Profile, Testimonial, Question, Answer, Event, EventGallery, Comment
from django.core.exceptions import ObjectDoesNotExist
from django import forms

class RegistrationForm(forms.Form):
    CHOICES = [( group.name, group.name ) for group in Group.objects.all()]
    
    username = forms.CharField(label='Username', max_length=30)
    email = forms.EmailField(label='Email')
    password1 = forms.CharField(label='Password',
                          widget=forms.PasswordInput())
    password2 = forms.CharField(label='Password (Again)',
                        widget=forms.PasswordInput())
    groupname = forms.ChoiceField(choices=CHOICES,widget = forms.widgets.RadioSelect())
    
    def clean_password2(self):
        if 'password1' in self.cleaned_data:
            password1 = self.cleaned_data['password1']
            password2 = self.cleaned_data['password2']
            if password1 == password2:
               return password2        
            raise forms.ValidationError('Passwords do not match.')
                

    def clean_username(self):
        username = self.cleaned_data['username']
        if not re.search(r'^\w+$', username):
            raise forms.ValidationError('Username can only contain alphanumeric characters and the underscore.')
        try:
            User.objects.get(username=username)
        except ObjectDoesNotExist:
            return username
        raise forms.ValidationError('Username is already taken.')


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('pic','bio','gender', 'city', 'batch', 'website','twitter','linkedin', 'organization')

class DeleteUserForm(forms.Form):
    username = forms.CharField()

class TestimonialForm(forms.ModelForm):
    class Meta:
        model = Testimonial
        fields = ('content',) 

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('title', 'description')

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ('answer',)

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ('title', 'icon', 'date', 'time', 'venue', 'description') 

class EventGalleryForm(forms.ModelForm):
    class Meta:
        model = EventGallery
        fields = ('pic',)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

class EmailForm(forms.Form):
    subject = forms.CharField(max_length=50)
    body = forms.CharField(widget = forms.Textarea())








    

core/templates/events/create_event.html
{% extends "header.html" %}

{% block style %}

.inva-a, .inva-a:hover {
    color:inherit;
    text-decoration: none;
}
textarea {
    width:100%;
    height:150px;
    resize:none;
    border-radius:4px;
    border:1px solid #ccc;
}

#id_icon {
    width: 0.1px;
    height: 0.1px;
    opacity: 0;
    overflow: hidden;
    position: absolute;
    z-index: -1;
}

.labelllll {
    font-size: 20px;
    float:right;
    font-family:Palatino Linotype;
}
#id_date, #id_time {
    width:100%;
    border:1px solid #ccc;
    border-radius:4px;
}

.icon-label {
    padding:10px;
    width:200px;
    color:white;
    background-color:#1b809e;
    border-radius:4px;
}

.icon-label:hover {
    opacity:0.6;
    outline: 1px dotted #000;
    outline: -webkit-focus-ring-color auto 5px;
}
{% endblock %}

{% block content %} 

    <h1> Create Your Event  </h1>
    
    <div class="col-md-3">
        <ul class="nav nav-pills nav-stacked">  
            <li role="presentation" ><a href="/event">Events Home</a></li>
            <li role="presentation" class="active"><a href="/event/createevent">Create Event </a></li>
            <li role="presentation" ><a href="/event/myevents">My Created Events</a></li>
            <li role="presentation" ><a href="/event/registeredevents">Registered Events</a></li>
        </ul>
    </div>
    <div class="col-md-9">
    
        <form enctype="multipart/form-data" method="post">
            {%csrf_token%}
            <div class="row">
            <div class="col-md-4">
                <p>Select Event Poster</p>
                {{event_form.icon}}
                <label for="id_icon" class="icon-label">Choose a file</label><br><br><br>
                <button type="submit" class="btn btn-primary"> Create </button>
            </div>
            <div class="col-md-8">
                <div class="row">
                    <div class="col-xs-4"><span class="labelllll">Title</span></div>
                    <div class="col-xs-8">{{event_form.title}}</div>
                </div>
                <div class="row">
                    <div class="col-xs-4"><span class="labelllll">Ajenda</span></div>
                    <div class="col-xs-8">{{event_form.description}}</div>
                </div>
                <div class="row">
                    <div class="col-xs-4"><span class="labelllll">Date</span></div>
                    <div class="col-xs-8">{{event_form.date}}</div>
                </div>
                <div class="row">
                    <div class="col-xs-4"><span class="labelllll">Time</span></div>
                    <div class="col-xs-8">{{event_form.time}}</div>
                </div>
                <div class="row">
                    <div class="col-xs-4"><span class="labelllll">Venue</span></div>
                    <div class="col-xs-8">{{event_form.venue}}</div>
                </div>
            </div>
            </div>
            
        </form>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script type="text/javascript">    
        $('#id_date').attr("type","date");
        $('#id_time').attr("type","time");
    </script>
{% endblock %}

<!-- form fields :
            'title', 'icon', 'date','time', 'venue', 'description'
-->

core/templates/events/event_home.html
{% extends "header.html" %}

{% block style %}
.event {
    border:1px solid #eee;
    padding:40px;
    margin-top:10px;
    border-radius:5px;
    border-left-color: #1b809e;
    border-left-width: 5px;
    background-color: #f7f7f9;
}

.in-detail {
    border:1px solid #ddd;
    border-radius:3px;    
    background-color:#fff;
    padding-left:5px;
    text-align:center;
}

.inva-a, .inva-a:hover {
    color:inherit;
    text-decoration: none;
}
{% endblock %}

{% block content %} 

    <h1>  Events  </h1>
    
    <div class="col-md-3">
        <ul class="nav nav-pills nav-stacked">  
            <li role="presentation" class="active"><a href="/event">Events Home</a></li>
            <li role="presentation" ><a href="/event/createevent">Create Event </a></li>
            <li role="presentation" ><a href="/event/myevents">My Created Events</a></li>
            <li role="presentation" ><a href="/event/registeredevents">Registered Events</a></li>
        </ul>
    </div>
    <div class="col-md-9">
    {%if eve %}
        {% for e in eve %}
            <div class="row event">
            <div class="col-md-3">
                <div class="row">
                    <img src="{{e.icon.url}}" alt="cannot display" height="100" width="100" class="center-block img-responsive img-rounded" />
                </div><hr>
                <div class="row">
                <center>
                    <img src="{{e.user.profile.pic.url}}" alt="can't display" height="50" width="50" class="img-responsive img-rounded"/>
                    <a href="{% url 'view_profile2' pk2=e.user.pk %}">{{e.user.get_full_name}} </a> 
                </center>
                </div>
            </div>
            <div class="col-md-9 in-detail">
                <div class="row">
                    <h2><a href="{% url 'view_event1' pk1=e.pk %}"> {{e.title}} </a></h2> 
                </div>
                <div class="row">
                    <b>Agenda :</b> {{e.description}}
                </div>
                <div class="row">
                    <b>Event Date :</b> {{e.date}}
                </div>
                <div class="row">
                    <b>Event Time :</b> {{e.time}}
                </div>
                <div class="row">
                    <b>Event Venue :</b> {{e.venue}}
                </div>
            </div>
                {%if not e.user == user %}
                    <a href="{% url 'register_for_event' pk3=e.pk %}" class="btn btn-primary inva-a"> Register </a>               
                {% endif %}
            </div>
         {% endfor %}
     {%else%}
        <p> No events to display </p>
    {% endif %}
    </div>
{% endblock %}

core/templates/events/my_event.html
{% extends "header.html" %}

{% block style %}
.event {
    border:1px solid #eee;
    padding:40px;
    margin-top:10px;
    border-radius:5px;
    border-left-color: #1b809e;
    border-left-width: 5px;
    background-color: #f7f7f9;
}

.in-detail {
    border:1px solid #ddd;
    border-radius:3px;    
    background-color:#fff;
    padding-left:5px;
    text-align:center;
}

{% endblock %}

{% block content %} 

    <h1>  Events  </h1>
    
    <div class="col-md-3">
        <ul class="nav nav-pills nav-stacked">  
            <li role="presentation" ><a href="/event">Events Home</a></li>
            <li role="presentation" ><a href="/event/createevent">Create Event </a></li>
            <li role="presentation" class="active"><a href="/event/myevents">My Created Events</a></li>
            <li role="presentation" ><a href="/event/registeredevents">Registered Events</a></li>
        </ul>
    </div>
    <div class="col-md-9">
    {%if eve %}
        {% for e in eve %}
            <div class="row event">
            <div class="row">
            <div class="col-md-3">
                <img src="{{e.icon.url}}" alt="cannot display" height="100" width="100" class="center-block img-responsive img-rounded" />
            </div>
            <div class="col-md-9 in-detail">
                <div class="row">
                    <h2><a href="{% url 'view_event2' pk1=e.pk %}"> {{e.title}} </a></h2> 
                </div>
                <div class="row">
                    <b>Agenda :</b> {{e.description}}
                </div>
                <div class="row">
                    <b>Event Date :</b> {{e.date}}
                </div>
                <div class="row">
                    <b>Event Time :</b> {{e.time}}
                </div>
                <div class="row">
                    <b>Event Venue :</b> {{e.venue}}
                </div>
            </div> 
            </div>           
                <a href="{% url 'delete_event' pk2=e.pk %}" class="btn btn-primary">Delete Event</a>
                <a href="{% url 'update_event_gallery' pk3=e.pk %}" class="btn btn-primary"> Update Event Gallery</a>
            </div>
         {% endfor %}
     {%else%}
        <p> No events to display </p>
    {% endif %}
    </div>
{% endblock %}

core/templates/events/post_comment.html
{% extends "header.html" %}
{% block title %}
<title>Add Comment</title>
{% endblock %}

{% block style %}
    	#id_content {
    		width:95%;
    		height:50px;
    		resize:none;
    		display:inline;
    		border-radius: 4px;
    		border:1px solid #ccc;
    	}

    	label {
    		width: 0.1px;
			height: 0.1px;
			opacity: 0;
			overflow: hidden;
			position: absolute;
			z-index: -1;
    	}

    	.btn-primary {
    		display: inline;
    		color: white;
    		background-color: #1b809e;
    		padding: 10px;
    		border-radius: 4px;
    		border:1px solid #ccc;
    	}
{% endblock %}

{% block error %}
<something></something>
{% endblock %}

{% block content %}
    <form method="post">
        {%csrf_token%}
        {{comment_form.as_p}}
        <button type="submit" class="btn-primary">post</button>
    </form>
{% endblock %}

<!-- form field : content-->

core/templates/events/registered_event.html
{% extends "header.html" %}

{% block style %}
.event {
    border:1px solid #eee;
    padding:40px;
    margin-top:10px;
    border-radius:5px;
    border-left-color: #1b809e;
    border-left-width: 5px;
    background-color: #f7f7f9;
}

.in-detail {
    border:1px solid #ddd;
    border-radius:3px;    
    background-color:#fff;
    padding-left:5px;
    text-align:center;
}

.inva-a, .inva-a:hover {
    color:inherit;
    text-decoration: none;
}
{% endblock %}

{% block content %} 

    <h1>  Events  </h1>
    
    <div class="col-md-3">
        <ul class="nav nav-pills nav-stacked">  
            <li role="presentation" ><a href="/event">Events Home</a></li>
            <li role="presentation" ><a href="/event/createevent">Create Event </a></li>
            <li role="presentation" ><a href="/event/myevents">My Created Events</a></li>
            <li role="presentation" class="active"><a href="/event/registeredevents">Registered Events</a></li>
        </ul>
    </div>
    <div class="col-md-9">
    {%if eve %}
        {% for e in eve %}
            <div class="row event">
            <div class="col-md-3">
                <div class="row">
                    <img src="{{e.icon.url}}" alt="cannot display" height="100" width="100" class="center-block img-responsive img-rounded" />
                </div><hr>
                <div class="row">
                <center>
                    <img src="{{e.user.profile.pic.url}}" alt="can't display" height="50" width="50" class="img-responsive img-rounded"/>
                    <a href="{% url 'view_profile3' pk2=e.user.pk %}">{{e.user.get_full_name}} </a> 
                </center>
                </div>
            </div>
            <div class="col-md-9 in-detail">
                <div class="row">
                    <h2><a href="{% url 'view_event3' pk1=e.pk %}"> {{e.title}} </a></h2> 
                </div>
                <div class="row">
                    <b>Agenda :</b> {{e.description}}
                </div>
                <div class="row">
                    <b>Event Date :</b> {{e.date}}
                </div>
                <div class="row">
                    <b>Event Time :</b> {{e.time}}
                </div>
                <div class="row">
                    <b>Event Venue :</b> {{e.venue}}
                </div>
            </div>
            </div>
         {% endfor %}
     {%else%}
        <p> No events to display </p>
    {% endif %}
    </div>
{% endblock %}

core/templates/events/upload_event_image.html
{% extends "header.html" %}

{% block title %}

<title>Upload Image | {{eve.title}}</title>

{% endblock %}

{% block style %}

#id_pic {
    padding:20px;
}

label {
    width: 0.1px;
    height: 0.1px;
    opacity: 0;
    overflow: hidden;
    position: absolute;
    z-index: -1;
}

{% endblock %}

{% block content %}

<h2>Upload Image To Image Gallery</h2>
<div class="row">
    <div class="col-md-3">
        <ul class="nav nav-pills nav-stacked">  
            <li role="presentation" ><a href="/event">Events Home</a></li>
            <li role="presentation" ><a href="/event/createevent">Create Event </a></li>
            <li role="presentation" ><a href="/event/myevents">My Created Events</a></li>
            <li role="presentation" ><a href="/event/registeredevents">Registered Events</a></li>
        </ul>
    </div>
    <div class="col-md-9">
        <h3> Upload Image For Event </h3>
        <p style="font-weight: bold;display: inline; "> Event title  </p>{{eve.title}}<br>
        <p style="font-weight: bold;display: inline;"> Event description </p>{{eve.description}}
        <form enctype="multipart/form-data" method="post">
            {%csrf_token%}
            {{image_upload_form.as_p}}
            <button type="submit" class="btn btn-primary" style="margin-left: 20px;width: 200px;"> Upload </button>
        </form>
    </div>
</div>
    

{% endblock %}
<!-- field is pic-->