alumni_support_system/urls.py
"""
Definition of urls for alumni_support_system.
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf.urls import include, url
from django.contrib.auth import views
from core import views as core_views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', alumni_support_system.views.home, name='home'),
    # url(r'^alumni_support_system/', include('alumni_support_system.alumni_support_system.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^$', core_views.home, name = 'home'),
    url(r'^login/$', views.login),
    url(r'^logout/$', views.logout, {'next_page' : '/login'}),
    url(r'^login/register/$', core_views.register_page),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^profile/$', core_views.view_profile, name = 'view_profile'),
    url(r'^profile/editprofile/$', core_views.update_profile, name='edit_profile'),
    url(r'^profile/writetestimonial/$', core_views.write_testimonial, name='write_testimonial'),
    url(r'^profile/viewtestimonial/$', core_views.view_testimonial, name='view_testimonial'),
    url(r'^profile/deletetestimonial/$', core_views.delete_testimonial, name='delete_testimonial'),
    url(r'^settings/$', core_views.settings, name='settings'), 
    url(r'^settings/changepassword/$', core_views.change_password, name='change_password'),
    url(r'^settings/deleteuser/$', core_views.delete_user, name='delete_user'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT})

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
     

core/urls.py
"""
Definition of urls for alumni_support_system.
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf.urls import include, url
from django.contrib.auth import views
from core import views as core_views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', alumni_support_system.views.home, name='home'),
    # url(r'^alumni_support_system/', include('alumni_support_system.alumni_support_system.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^$', core_views.home, name = 'home'),
    url(r'^login/$', views.login),
    url(r'^logout/$', views.logout, {'next_page' : '/login'}),
    url(r'^login/register/$', core_views.register_page),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    
    url(r'^profile/$', core_views.view_profile, name = 'view_profile'),
    url(r'^profile/editprofile/$', core_views.update_profile, name='edit_profile'),
    url(r'^profile/writetestimonial/$', core_views.write_testimonial, name='write_testimonial'),
    url(r'^profile/viewtestimonial/$', core_views.view_testimonial, name='view_testimonial'),
    url(r'^profile/deletetestimonial/$', core_views.delete_testimonial, name='delete_testimonial'),
    
    url(r'^settings/$', core_views.settings, name='settings'), 
    url(r'^settings/changepassword/$', core_views.change_password, name='change_password'),
    url(r'^settings/deleteuser/$', core_views.delete_user, name='delete_user'),
    
    url(r'^questionanswer/$', core_views.question_answer, name='question_answer_home'),
    url(r'^questionasnwer/askquestion/$', core_views.post_question, name='post_question'),
    url(r'^questionanswer/answerquestion/(?P<pk>\d+)/$', core_views.post_answer, name='post_answer'),
    url(r'^questionanswer/viewanswers/(?P<pk>\d+)/$', core_views.view_answer, name='view_answer'),
    url(r'^questionanswer/viewaskedquestions/$', core_views.view_asked_question, name='view_asked_question'),
    url(r'^questionanswer/viewaskedquestions/viewanswers/(?P<pk>\d+)/$', core_views.view_answer, name='view_answer2'),
    url(r'^questionanswer/viewansweredquestions/$', core_views.view_answered_question, name='view_answered_question'),
    url(r'^questionanswer/viewansweredquestions/viewanswers/(?P<pk>\d+)/$', core_views.view_answer, name='view_answer3'),
    url(r'^questionanswer/viewunansweredquestions/$', core_views.view_unanswered_question, name = 'view_unanswered_question'),
    url(r'^questionanswer/viewaskedquestions/deletequestion/(?P<pk2>\d+)/$', core_views.delete_question, name = 'delete_question'),
    #url(r'^questionanswer/viewanswers/(?P<pk>\d+)/deleteanswer/(?P<pk2>\d+)/$', core_views.delete_answer, name='delete_answer'),
    #url(r'^questionanswer/viewaskedquestions/viewanswers/(?P<pk>\d+)/deleteanswer/(?P<pk2>\d+)/$', core_views.delete_answer, name='delete_answer'),
    #url(r'^questionanswer/viewansweredquestions/viewanswers/(?P<pk>\d+)/deleteanswer/(?P<pk2>\d+)/$', core_views.delete_answer, name='delete_answer'),

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT})

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
     

core/models.py
import os
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import datetime,date


# Create your models here.

#NOTE : delete all users from admin before making any changes to model

#to save user dp in media/users/user_id/filename
def get_image_path(instance, filename):
    return os.path.join('users', str(instance.id), filename)

#dummy just ignore
def get_event_image_path(instance, filename):
    return os.path.join('events', str(instance.id), filename)


class Profile(models.Model):
    
    BATCH_CHOICES = (
        ('NA', 'Not Applicable'),
        ('1998','1998'),
        ('1999','1999'),
        ('2000','2000'),
        ('2001','2001'),
        ('2002','2002'),
        ('2003','2003'),
        ('2004','2004'),
        ('2005','2005'),
        ('2006','2006'),
        ('2007','2007'),
        ('2008','2008'),
        ('2009','2009'),
        ('2010','2010'),
        ('2011','2011'),
        ('2012','2012'),
        ('2013','2013'),
        ('2014','2014'),
        ('2015','2015'),
        ('2016','2016'),
        )

    
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        )

    
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    pic = models.ImageField(upload_to=get_image_path, default = os.path.join('users', 'default_avatar.jpg'))
    bio = models.TextField(max_length=500, default = '', blank=True)
    gender = models.CharField(max_length=1, choices = GENDER_CHOICES, blank = True)
    city = models.CharField(max_length=30,default = '', blank=True)
    batch = models.CharField(max_length=4, choices = BATCH_CHOICES, blank=True)
    website = models.URLField(default='', blank=True)
    twitter = models.URLField(default='', blank=True)
    linkedin = models.URLField(default='', blank=True)
    organization = models.CharField(max_length=100, default='', blank=True)

#so that profile is created and saved each time a user is created
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Testimonial(models.Model):
    user = models.OneToOneField(User, null = True, on_delete = models.CASCADE)
    content = models.TextField(max_length = 1000, default = '', blank =  True)
    pub_date = models.DateTimeField(auto_now_add = True)


class Question(models.Model):
    user = models.ForeignKey(User, null = True, on_delete = models.CASCADE)
    title = models.TextField(max_length = 200)
    description = models.TextField(max_length = 500, default = '', blank = True)
    pub_date = models.DateTimeField(auto_now_add = True)


class Answer(models.Model):
    user = models.ForeignKey(User, null = True, on_delete = models.CASCADE)
    question = models.ForeignKey(Question, null = True, on_delete = models.CASCADE)
    answer = models.TextField(max_length = 1000)
    pub_date = models.DateTimeField(auto_now_add = True)
 

class Event(models.Model):
    user = models.ForeignKey(User, null = True, on_delete = models.CASCADE)
    title = models.TextField(max_length = 50)
    date = models.DateField(default = date.today)
    time = models.TimeField(default = datetime.now)
    venue = models.TextField(max_length = 50)
    description = models.TextField(max_length = 500, blank = True, default = '')
    icon = models.ImageField(upload_to=get_image_path, default = os.path.join('users', 'default_icon.jpg'))
    pub_date = models.DateTimeField(auto_now_add = True)
 

class EventAttendees(models.Model):
    user = models.ForeignKey(User, null = True, on_delete = models.CASCADE)
    event = models.ForeignKey(Event, null = True, on_delete = models.CASCADE)


class EventGallery(models.Model):
    user = models.ForeignKey(User, null = True, on_delete = models.CASCADE)
    event = models.ForeignKey(Event, null = True, on_delete = models.CASCADE)
    pic = models.ImageField(upload_to = get_image_path, blank = True, null = True)
    pub_date = models.DateTimeField(auto_now_add = True)


class Comment(models.Model):
    user = models.ForeignKey(User, null = True, on_delete = models.CASCADE)
    event = models.ForeignKey(Event, null = True, on_delete = models.CASCADE)
    content = models.TextField(max_length = 200)
    pub_date = models.DateTimeField(auto_now_add = True)
   

core/forms.py
import re
from django.contrib.auth.models import User, Group
from core.models import Profile, Testimonial, Question, Answer, Event, EventGallery, Comment
from django.core.exceptions import ObjectDoesNotExist
from django import forms

class RegistrationForm(forms.Form):
    CHOICES = [( group.name, group.name ) for group in Group.objects.all()]
    
    username = forms.CharField(label='Username', max_length=30)
    email = forms.EmailField(label='Email')
    password1 = forms.CharField(label='Password',
                          widget=forms.PasswordInput())
    password2 = forms.CharField(label='Password (Again)',
                        widget=forms.PasswordInput())
    groupname = forms.ChoiceField(choices=CHOICES,widget = forms.widgets.RadioSelect())
    
    def clean_password2(self):
        if 'password1' in self.cleaned_data:
            password1 = self.cleaned_data['password1']
            password2 = self.cleaned_data['password2']
            if password1 == password2:
               return password2        
            raise forms.ValidationError('Passwords do not match.')
                

    def clean_username(self):
        username = self.cleaned_data['username']
        if not re.search(r'^\w+$', username):
            raise forms.ValidationError('Username can only contain alphanumeric characters and the underscore.')
        try:
            User.objects.get(username=username)
        except ObjectDoesNotExist:
            return username
        raise forms.ValidationError('Username is already taken.')


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('pic','bio','gender', 'city', 'batch', 'website','twitter','linkedin', 'organization')

class DeleteUserForm(forms.Form):
    username = forms.CharField()

class TestimonialForm(forms.ModelForm):
    class Meta:
        model = Testimonial
        fields = ('content',) 

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('title', 'description')

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ('answer',)

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ('title', 'icon', 'date', 'time', 'venue', 'description') 

class EventGalleryForm(forms.ModelForm):
    class Meta:
        model = EventGallery
        fields = ('pic',)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

class EmailForm(forms.Form):
    subject = forms.CharField(max_length=50)
    body = forms.CharField(widget = forms.Textarea())








    

core/templates/profiles/edit_profile.html
{% extends 'header.html' %}
{% block title %}
<title>{{user.get_full_name}} | Alumni Support System</title>
{% endblock %}

{% block style %}
input, select {
    width:100%;
    height:100%;
    border:0px solid;
    outline:none;
    background-color: transparent;
}

textarea {
    width:100%;
    height:150px;
    resize:none;
    border:1px solid grey;
    border-radius:5px;
}

#id_twitter, #id_linkedin {
    border:none;
    outline:none;
    height:100%;
    width:100%;
}

.hidden {
    width: 0.1px;
    height: 0.1px;
    opacity: 0;
    overflow: hidden;
    position: absolute;
    z-index: -1;
}
{% endblock %}

{% block content %}
        <br><br>
    <div class="row">
        <div class="col-md-3">
            <form method="post" enctype="multipart/form-data">
             {% csrf_token %}
            <center>
            <span class="hidden">{{profile_form.pic}}</span>
            <label for="id_pic"><img src="{{user.profile.pic.url}}" alt="hf" class="img-responsive img-rounded center-block"></label>
            <p>click the picture to change it</p>
            <h3>{{user.get_full_name}}</h3></center>          
            <div class="row input-group">
                <label for="id_twitter" class="fa fa-twitter input-group-addon" style="size: 36px;color: #1b809e"></label>
                <span class="form-control">{{profile_form.twitter}}</span>
            </div>
            <div class="row input-group">
                <label fdr="id_linkedin" class="fa fa-linkedin input-group-addon" style="size: 36px;color: #1b809e"></label>
                <span class="form-control">{{profile_form.linkedin}}</span>
            </div>
            <hr>
            <ul class="nav nav-pills nav-stacked">  
                <li role="presentation"><a href="/profile">View Profile</a></li>
                <li role="presentation" class="active"><a href="/profile/editprofile">Edit profile</a></li>
                <li role="presentation"><a href="/settings/changepassword">Change Password</a></li>
                <li role="presentation"><a href="/settings/deleteuser">Delete User</a></li>
            </ul>
        </div>
        <div class="col-md-6" style="padding-left: 30px">
        
           
            <div class="row">
            <h3>BIO</h3> {{profile_form.bio}}   
            </div><br>
            <div class="row input-group">
                <span class="input-group-addon">First Name</span>
                <span class="form-control">{{user_form.first_name}}</span>
            </div>
            <div class="row input-group">
                <span class="input-group-addon">Last Name</span>
                <span class="form-control">{{user_form.last_name}}</span>
            </div>
            <div class="row input-group">
                <span class="input-group-addon"> Email </span>
                <span class="form-control">{{user_form.email}}</span>
            </div>
            <div class="row input-group">
                <label for="id_batch" class="input-group-addon">Batch</label>
                <span class="form-control">{{profile_form.batch}}</span>
            </div>
            <div class="row input-group">
                <span class="input-group-addon">Location</span>
                <span class="form-control">{{profile_form.city}}</span>
            </div>
            <div class="row input-group">
                <span class="input-group-addon">Currently Working at</span>
                <span class="form-control">{{profile_form.organization}}</span>
            </div>
            <div class="row input-group">
                <span class="input-group-addon">Website</span>
                <span class="form-control">{{profile_form.website}}</span>
            </div><br>
            <div class="row">
                <button type="submit" class="btn btn-primary">Save changes</button>
            </div>
            </form>
        </div>
        <div class="col-md-3">
        <h3>Your Content</h3>
            <ul class="nav nav-pills nav-stacked">
                <li role="presentation"><a href="/profile/viewtestimonial/">View Testimonials</a></li>
                <li role="presentation"><a href="/profile/writetestimonial/">Write Testimonials</a></li>
                <li role="presentation"><a href="/questionanswer/viewaskedquestions/">Asked Questions</a></li>
            </ul>
        </div>
    </div>
{% endblock %}

core/templates/profiles/view_profile.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>View Profile </title>
</head>
<body>
    {% if messages %}
        <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
        </ul>
    {% endif %}
    <h1> Profile : </h1>
    <h2> Name : {{user.get_full_name}}</h2>
    <ul>
        <li> Username : {{user.username}}</li>
        <li> Dp : <img src="{{user.profile.pic.url}}" alt="can't display" height="100" width="100" />
        <li> Email : {{user.email}}</li>
        <li> Bio : {{user.profile.bio}}</li>
        <li> DOB : {{user.profile.birth_date}}</li>
        <li>Batch : {{user.profile.batch}}</li>
        <li> City : {{user.profile.city}}</li>
        <li> Organization : {{user.profile.organization}}</li>
        <li> Website : {{user.profile.website}}</li>
    </ul>
    <a href="/profile/editprofile"> Edit Profile</a>
    <a href="/">Home</a>
</body>
</html>

core/templates/profiles/view_profile2.html
{% extends 'header.html' %}
{% block title %}
<title>{{user.get_full_name}} | Alumni Support System</title>
{% endblock %}

{% block style %}
.skip {
    width: 0.1px;
    height: 0.1px;
    opacity: 0;
    overflow: hidden;
    position: absolute;
    z-index: -1;
}
{% endblock %}

{% block content %}
        <br><br>
    <div class="row">
        <div class="col-md-3">
            <img src="{{user.profile.pic.url}}" alt=":/" class="img-responsive img-rounded center-block">
            
            <center><h3 class="center-block">{{user.get_full_name}}</h3></center>
            <div class="row">
            <center>
            {% if user.profile.twitter %}
                <a href="{{user.profile.twitter}}" class="fa fa-twitter" style="font-size: 36px;color:#1b809e;text-decoration: none"></a>
            {% endif %}
            {% if user.profile.linkedin %}
                <a href="{{user.profile.linkedin}}" class="fa fa-linkedin" style="font-size: 36px;color:#1b809e;text-decoration: none"></a>
            {% endif %}
            </center>
            </div>
        </div>
        <div class="col-md-6">
            <div class="row">
                    <h2>{{user.get_full_name}}</h2>
            </div>
            <div class="row">
                    <h3>
                        {{user.profile.bio}}
                    </h3>
            </div><br>
            {% if user.email %}
            <div class="row input-group">
                <span class="input-group-addon"> Email </span>
                <span class="form-control">{{user.email}}</span>
            </div>
            {% endif %}
            {% if user.profile.batch %}
            <div class="row input-group">
                <span class="input-group-addon">Batch</span>
                <span class="form-control">{{user.profile.batch}}</span>
            </div>
            {% endif %}
            {% if user.profile.city %}
            <div class="row input-group">
                <span class="input-group-addon">Location</span>
                <span class="form-control">{{user.profile.city}}</span>
            </div>
            {% endif %}
            {% if user.profile.gender %}
            <div class="row input-group">
                <span class="input-group-addon">Gender</span>               
                <span class="form-control">{{user.profile.gender}}</span>
            </div>
            {% endif %}
            {% if user.profile.organization %}
            <div class="row input-group">
                <span class="input-group-addon">Currently Working at</span>
                <span class="form-control">{{user.profile.organization}}</span>
            </div>
            {% endif %}
            {% if user.profile.website %}
            <div class="row input-group">
                <span class="input-group-addon">Website</span>
                <span class="form-control">{{user.profile.website}}</span>
            </div>
            {% endif %}
        </div>
    </div>

{% endblock %}

core/templates/profiles/view_testimonial.html
{% extends 'header.html' %}
{% block title %}
<title>Your Testimonials</title>
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-md-8">
            <center><h2 style="color: #666;font-family:Palatino Linotype;"><i>&quot;{{testimonial.content}}&quot;</i></h2></center>
        </div>
        <div class="col-md-4">
            <ul class="nav nav-pills nav-stacked">
                <li role="presentation" class="active"><a href="/profile/viewtestimonial/">View Testimonials</a></li>
                <li role="presentation"><a href="/profile/writetestimonial/">Write Testimonials</a></li>
                <li role="presentation"><a href="/questionanswer/viewaskedquestions/">Asked Questions</a></li>
            </ul>
        </div>
    </div>
{% endblock %}

core/templates/profiles/write_testimonial.html
{% extends 'header.html' %}

{% block title %}
<title>Write Testimonial</title>
{% endblock %}

{% block style %}
#id_content {
    width:550px;
    height:200px;
    resize:none;
    border-radius:4px;
    border:1px solid #ccc;
}

label {
    width: 0.1px;
    height: 0.1px;
    opacity: 0;
    overflow: hidden;
    position: absolute;
    z-index: -1;    
}
{% endblock %}

{% block content %}

    <div class="row">
    <div class="col-md-8">
    <center>
    <h1>Write Testimonial</h1>
    <h3>write something about the college</h3>
    </center>
    <form method="post" action="">
        {%csrf_token%}
        <center>
        {{testimonial_form.as_p}}
        <button type="submit" class="btn btn-primary">Save </button></center>
    </form>
    </div>
    <div class="col-md-4">
        <ul class="nav nav-pills nav-stacked">
            <li role="presentation"><a href="/profile/viewtestimonial/">View Testimonials</a></li>
            <li role="presentation" class="active"><a href="/profile/writetestimonial/">Write Testimonials</a></li>
            <li role="presentation"><a href="/questionanswer/viewaskedquestions/">Asked Questions</a></li>
        </ul>
    </div>


{% endblock %}