alumni_support_system/urls.py
"""
Definition of urls for alumni_support_system.
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf.urls import include, url
from django.contrib.auth import views
from core import views as core_views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', alumni_support_system.views.home, name='home'),
    # url(r'^alumni_support_system/', include('alumni_support_system.alumni_support_system.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^$', core_views.home, name = 'home'),
    url(r'^login/$', views.login),
    url(r'^logout/$', views.logout, {'next_page' : '/login'}),
    url(r'^login/register/$', core_views.register_page),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^profile/$', core_views.view_profile, name = 'view_profile'),
    url(r'^profile/editprofile/$', core_views.update_profile, name='edit_profile'),
    url(r'^profile/writetestimonial/$', core_views.write_testimonial, name='write_testimonial'),
    url(r'^profile/viewtestimonial/$', core_views.view_testimonial, name='view_testimonial'),
    url(r'^profile/deletetestimonial/$', core_views.delete_testimonial, name='delete_testimonial'),
    url(r'^settings/$', core_views.settings, name='settings'), 
    url(r'^settings/changepassword/$', core_views.change_password, name='change_password'),
    url(r'^settings/deleteuser/$', core_views.delete_user, name='delete_user'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT})

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
     

core/urls.py
"""
Definition of urls for alumni_support_system.
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf.urls import include, url
from django.contrib.auth import views
from core import views as core_views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', alumni_support_system.views.home, name='home'),
    # url(r'^alumni_support_system/', include('alumni_support_system.alumni_support_system.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^$', core_views.home, name = 'home'),
    url(r'^login/$', views.login),
    url(r'^logout/$', views.logout, {'next_page' : '/login'}),
    url(r'^login/register/$', core_views.register_page),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    
    url(r'^profile/$', core_views.view_profile, name = 'view_profile'),
    url(r'^profile/editprofile/$', core_views.update_profile, name='edit_profile'),
    url(r'^profile/writetestimonial/$', core_views.write_testimonial, name='write_testimonial'),
    url(r'^profile/viewtestimonial/$', core_views.view_testimonial, name='view_testimonial'),
    url(r'^profile/deletetestimonial/$', core_views.delete_testimonial, name='delete_testimonial'),
    
    url(r'^settings/$', core_views.settings, name='settings'), 
    url(r'^settings/changepassword/$', core_views.change_password, name='change_password'),
    url(r'^settings/deleteuser/$', core_views.delete_user, name='delete_user'),
    
    url(r'^questionanswer/$', core_views.question_answer, name='question_answer_home'),
    url(r'^questionasnwer/askquestion/$', core_views.post_question, name='post_question'),
    url(r'^questionanswer/answerquestion/(?P<pk>\d+)/$', core_views.post_answer, name='post_answer'),
    url(r'^questionanswer/viewanswers/(?P<pk>\d+)/$', core_views.view_answer, name='view_answer'),
    url(r'^questionanswer/viewaskedquestions/$', core_views.view_asked_question, name='view_asked_question'),
    url(r'^questionanswer/viewaskedquestions/viewanswers/(?P<pk>\d+)/$', core_views.view_answer, name='view_answer2'),
    url(r'^questionanswer/viewansweredquestions/$', core_views.view_answered_question, name='view_answered_question'),
    url(r'^questionanswer/viewansweredquestions/viewanswers/(?P<pk>\d+)/$', core_views.view_answer, name='view_answer3'),
    url(r'^questionanswer/viewunansweredquestions/$', core_views.view_unanswered_question, name = 'view_unanswered_question'),
    url(r'^questionanswer/viewaskedquestions/deletequestion/(?P<pk2>\d+)/$', core_views.delete_question, name = 'delete_question'),
    #url(r'^questionanswer/viewanswers/(?P<pk>\d+)/deleteanswer/(?P<pk2>\d+)/$', core_views.delete_answer, name='delete_answer'),
    #url(r'^questionanswer/viewaskedquestions/viewanswers/(?P<pk>\d+)/deleteanswer/(?P<pk2>\d+)/$', core_views.delete_answer, name='delete_answer'),
    #url(r'^questionanswer/viewansweredquestions/viewanswers/(?P<pk>\d+)/deleteanswer/(?P<pk2>\d+)/$', core_views.delete_answer, name='delete_answer'),

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT})

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
     

core/models.py
import os
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import datetime,date


# Create your models here.

#NOTE : delete all users from admin before making any changes to model

#to save user dp in media/users/user_id/filename
def get_image_path(instance, filename):
    return os.path.join('users', str(instance.id), filename)

#dummy just ignore
def get_event_image_path(instance, filename):
    return os.path.join('events', str(instance.id), filename)


class Profile(models.Model):
    
    BATCH_CHOICES = (
        ('NA', 'Not Applicable'),
        ('1998','1998'),
        ('1999','1999'),
        ('2000','2000'),
        ('2001','2001'),
        ('2002','2002'),
        ('2003','2003'),
        ('2004','2004'),
        ('2005','2005'),
        ('2006','2006'),
        ('2007','2007'),
        ('2008','2008'),
        ('2009','2009'),
        ('2010','2010'),
        ('2011','2011'),
        ('2012','2012'),
        ('2013','2013'),
        ('2014','2014'),
        ('2015','2015'),
        ('2016','2016'),
        )

    
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        )

    
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    pic = models.ImageField(upload_to=get_image_path, default = os.path.join('users', 'default_avatar.jpg'))
    bio = models.TextField(max_length=500, default = '', blank=True)
    gender = models.CharField(max_length=1, choices = GENDER_CHOICES, blank = True)
    city = models.CharField(max_length=30,default = '', blank=True)
    batch = models.CharField(max_length=4, choices = BATCH_CHOICES, blank=True)
    website = models.URLField(default='', blank=True)
    twitter = models.URLField(default='', blank=True)
    linkedin = models.URLField(default='', blank=True)
    organization = models.CharField(max_length=100, default='', blank=True)

#so that profile is created and saved each time a user is created
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Testimonial(models.Model):
    user = models.OneToOneField(User, null = True, on_delete = models.CASCADE)
    content = models.TextField(max_length = 1000, default = '', blank =  True)
    pub_date = models.DateTimeField(auto_now_add = True)


class Question(models.Model):
    user = models.ForeignKey(User, null = True, on_delete = models.CASCADE)
    title = models.TextField(max_length = 200)
    description = models.TextField(max_length = 500, default = '', blank = True)
    pub_date = models.DateTimeField(auto_now_add = True)


class Answer(models.Model):
    user = models.ForeignKey(User, null = True, on_delete = models.CASCADE)
    question = models.ForeignKey(Question, null = True, on_delete = models.CASCADE)
    answer = models.TextField(max_length = 1000)
    pub_date = models.DateTimeField(auto_now_add = True)
 

class Event(models.Model):
    user = models.ForeignKey(User, null = True, on_delete = models.CASCADE)
    title = models.TextField(max_length = 50)
    date = models.DateField(default = date.today)
    time = models.TimeField(default = datetime.now)
    venue = models.TextField(max_length = 50)
    description = models.TextField(max_length = 500, blank = True, default = '')
    icon = models.ImageField(upload_to=get_image_path, default = os.path.join('users', 'default_icon.jpg'))
    pub_date = models.DateTimeField(auto_now_add = True)
 

class EventAttendees(models.Model):
    user = models.ForeignKey(User, null = True, on_delete = models.CASCADE)
    event = models.ForeignKey(Event, null = True, on_delete = models.CASCADE)


class EventGallery(models.Model):
    user = models.ForeignKey(User, null = True, on_delete = models.CASCADE)
    event = models.ForeignKey(Event, null = True, on_delete = models.CASCADE)
    pic = models.ImageField(upload_to = get_image_path, blank = True, null = True)
    pub_date = models.DateTimeField(auto_now_add = True)


class Comment(models.Model):
    user = models.ForeignKey(User, null = True, on_delete = models.CASCADE)
    event = models.ForeignKey(Event, null = True, on_delete = models.CASCADE)
    content = models.TextField(max_length = 200)
    pub_date = models.DateTimeField(auto_now_add = True)
   

core/forms.py
import re
from django.contrib.auth.models import User, Group
from core.models import Profile, Testimonial, Question, Answer, Event, EventGallery, Comment
from django.core.exceptions import ObjectDoesNotExist
from django import forms

class RegistrationForm(forms.Form):
    CHOICES = [( group.name, group.name ) for group in Group.objects.all()]
    
    username = forms.CharField(label='Username', max_length=30)
    email = forms.EmailField(label='Email')
    password1 = forms.CharField(label='Password',
                          widget=forms.PasswordInput())
    password2 = forms.CharField(label='Password (Again)',
                        widget=forms.PasswordInput())
    groupname = forms.ChoiceField(choices=CHOICES,widget = forms.widgets.RadioSelect())
    
    def clean_password2(self):
        if 'password1' in self.cleaned_data:
            password1 = self.cleaned_data['password1']
            password2 = self.cleaned_data['password2']
            if password1 == password2:
               return password2        
            raise forms.ValidationError('Passwords do not match.')
                

    def clean_username(self):
        username = self.cleaned_data['username']
        if not re.search(r'^\w+$', username):
            raise forms.ValidationError('Username can only contain alphanumeric characters and the underscore.')
        try:
            User.objects.get(username=username)
        except ObjectDoesNotExist:
            return username
        raise forms.ValidationError('Username is already taken.')


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('pic','bio','gender', 'city', 'batch', 'website','twitter','linkedin', 'organization')

class DeleteUserForm(forms.Form):
    username = forms.CharField()

class TestimonialForm(forms.ModelForm):
    class Meta:
        model = Testimonial
        fields = ('content',) 

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('title', 'description')

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ('answer',)

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ('title', 'icon', 'date', 'time', 'venue', 'description') 

class EventGalleryForm(forms.ModelForm):
    class Meta:
        model = EventGallery
        fields = ('pic',)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

class EmailForm(forms.Form):
    subject = forms.CharField(max_length=50)
    body = forms.CharField(widget = forms.Textarea())








    

core/templates/about_us.html
{% extends "header.html" %}
{% block title %}
<title>About Us</title>
{% endblock %}

{% block style %}
.testi {
	border:1px solid #eee;
    padding:10px;
    margin-top:10px;
    border-radius:5px;
    background-color: #f7f7f9;
}
{% endblock %}

{% block content %}
<div class="row">
<center><h1>About Us</h1></center>
	<script type="text/javascript" src="https://platform.linkedin.com/badges/js/profile.js" async defer></script>
	<div class="row">
		<h2 style="color: #666;font-family:Palatino Linotype;"><center>
		<i>&quot;We are a bunch of geeks working towards the betterment of the society around us&quot;</i>
		</center></h2>
	</div>
	<br><br>
	<div class="center-block row">
		<center>
			<div class="col-md-6">
				<div class="LI-profile-badge"  data-version="v1" data-size="medium" data-locale="en_US" data-type="vertical" data-theme="light" data-vanity="anmoljindal"><a class="LI-simple-link" href='https://in.linkedin.com/in/anmoljindal?trk=profile-badge'>Anmol Jindal</a></div>
			</div>
			<div class="col-md-6">
				<div class="LI-profile-badge"  data-version="v1" data-size="medium" data-locale="en_US" data-type="vertical" data-theme="light" data-vanity="siddhartha-jha-bb16aa13a"><a class="LI-simple-link" href='https://in.linkedin.com/in/siddhartha-jha-bb16aa13a?trk=profile-badge'>Siddhartha Jha</a></div>
			</div>
		</center>
	</div>
</div>
{% endblock %}

core/templates/career_services_deptt.html
{% extends "header.html" %}

{% block title %}
<title>Career Services | Alumni Support System</title>
{% endblock %}

{% block style %}

.testi {
    border:1px solid #eee;
    padding:40px;
    margin-top:10px;
    border-radius:5px;
    border-left-color: #1b809e;
    border-left-width: 5px;
    background-color: #f7f7f9;
}

#id_subject {
    width:390px;
    height:50px;
    border:1px solid #ccc;
    border-radius:4px;    

}

#id_body {
    width:380px;
    height:200px;
    resize:none;
    border:1px solid #ccc;
    border-radius:4px;
}

{% endblock %}

{% block content %}
    <center><h1> Career Services Department </h1></center>
    <div class="row testi">      
<h2 style="color: #666;font-family:Palatino Linotype;"><center>
Career Services Department continuously strives to help students in pursuing their career goals by acquiring employment-seeking skills and ultimately to attain desired employment. This is accomplished through building a strong partnership amongst students, alumni, faculty members and industries.

The University follows a centralized placement activity which gives each branch equal opportunity to grow for sustained excellence in career through training & placement.
</center></h2>
    </div>
    
    <form method="post">
        {%csrf_token%}
        <div class="row">
        <center>
            <p style="font-size: 30px;"> You can mail us your query using the form below </p>
            {{email_form.as_p}}
            <button type="submit" class="btn btn-primary">Send Mail</button>
        </center>
        </div>
    </form>
{% endblock %}

<!--Fields are subject and body-->

core/templates/header.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}
    <title>Alumni</title>
    {% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" >
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {% load staticfiles %}
   <!-- <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css"> -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <style>
        body {padding: 70px; }

        .row {
            margin: 5px;
        }

        .icon-pic {
            height: 40px;
            width: 40px;
        }
        
        #dopper {
            background-color: inherit;
            color: #888888;
            border:none;
        }

        .errormsg {
            background-color: #4286f4;
            font-family: sans-serif;
            padding: 10px;
            text-align: center;
            width: 100%;
            list-style: none;
        }

        {% block style %}
            
        {% endblock %}
    </style>
</head>
<body>
<div class="body">
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
            <a class="navbar-brand" href="/">
                Alumni Support System
            </a>
            </div>
            <div>
                <ul class="nav navbar-nav">
                    <li><a href="/questionanswer">Forum</a></li>
                    <li><a href="/event">Events</a></li>
                    <li><a href="/testimonial">Testimonials</a></li>
                    <li><a href="/careerservicesdepartment">Career Services</a></li>
                    <li><a href="/people">People</a></li>
                </ul>
            </div>
             <div class="dropdown navbar-right skip">
                <button id="dopper" class="btn btn-default dropdown-toggle " type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                    {{user.get_full_name}}
                    {% if user.profile.pic %}
                    <img src="{{user.profile.pic.url}}" class="img-circle icon-pic">
                    {% endif %}
                    <span class="caret"></span>
                </button >
                <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                    <li><a href="/profile">View Profile</a></li>
                    <li><a href="/profile/editprofile">Edit Profile</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="/logout">Logout</a></li>
                </ul>
            </div>
        </div>
    </nav>
        {% block error %}
        {% if messages %}
            <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }} errormsg"{% endif %}>{{ message }}</li>
            {% endfor %}
            </ul>
        {% endif %}
        {% endblock %}
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    <!---footer-->
    <div class="container">
        <hr class="featurette-divider">
        <footer>
            <br><br>
            <p class="pull-right"><a href="#">Back to top</a></p>
            <p>&copy; 2017 Anmol Jindal &middot; Siddhartha Jha &middot; <a href="/aboutus">About Us</a></p>
            <br><br>
        </footer>
    </div>
</div>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
</body>

</html>

core/templates/home.html
{% extends "header.html" %}
{% block style %}
.fiel {
    display:block;
    font-size:18px;
    font-family:Palatino Linotype;
}
.hidden {
    width: 0.1px;
    height: 0.1px;
    opacity: 0;
    overflow: hidden;
    position: absolute;
    z-index: -1;
}
{% endblock %}

{% block content %}

<div class="hidden">
{%if user.username %}
    <p>Welcome {{user.first_name}}! </p>
    <a href="profile">view profile</a>      
    <a href="logout">logout</a>
    <a href="settings">settings</a>
    <a href="questionanswer"> q &amp; a</a>
    <a href="event">events</a>
    <a href="people">people</a>
    <a href="careerservicesdepartment">Career Services Department</a>
    <a href="testimonial">Testimonials</a>
{%endif%}
</div>
<!--Photo references-->
<div class="row">
	<center><h3>Alumni Association Members</h3><br>
    <i>
	<div class="col-md-6" style="font-size:17px;color: #888;">
		<center>
        <img src= "" class="img-circle" alt="image not found" height="50" width="50">
		<p>Anmol Jindal<br>Microsoft<br>2014-2018</p>	
	   </center>
    </div>
	<div class="col-md-6" style="font-size:17px;color: #888;">
		<center>
        <img src="#" class="img-circle" alt="image not found" height="50" width="50">
		<p>Siddhartha jha<br>Google<br>2014-2018</p>	
        </center>
    </div>
    </i>
    </center>
</div>
<hr class="featurette-divider">
<div class="row">
<div class="col-md-9">
	<div class="row">
    <center><h3>Testimonial</h3></center>
    {% if test %}
    <div class="row">
        {% for t in test %}
            <div class="row">
                <h2 style="color: #666;font-family:Palatino Linotype;"><i>&quot;{{t.content}}&quot;</i></h2>
                <span style="font-size:16px;"><strong>-{{t.user.get_full_name}}</strong></span>
            </div>
        {% endfor %}
    </div>
    {% endif %}
    </div><hr>
    <div class="row">
         <center><h3>Memories</h3></center>
     {% if gal %}
     <div class="row">
        {% for g in gal %}
            <div class="col-md-4" style="margin-bottom:10px;">
                <img src="{{g.pic.url}}" alt="cannot display" height="100%" width="100%" class="img-rounded" />
            </div>
        {% endfor %}
    </div>
    {% endif %}
    </div>
</div>
<div class="col-md-3">
    <center><h3>Events</h3></center>
    {% if eve %}
        {% for e in eve %}
            <div class="row">
            <center>
                <span class="fiel"><a href="{% url 'view_event4' pk1=e.pk %}"> {{e.title}} </a></span>
                <span class="fiel">{{e.venue}}</span>
                <span class="fiel">{{e.date}}</span>
                <span class="fiel">{{e.time}}</span>
            </center>
            </div>
        {% endfor %}
    {% endif %}
</div>
   
{% endblock %}

core/templates/index.html
<html>
<head><title></title></head>

<body>

{{ content }}

</body>
</html>

core/templates/people.html
{% extends "header.html" %}

{% block title %}

<title>People | Alumni Support System</title>

{% endblock %}

{% block style %}
.skip {
    width: 0.1px;
    height: 0.1px;
    opacity: 0;
    overflow: hidden;
    position: absolute;
    z-index: -1;
}

.testi {
    border:1px solid #eee;
    padding:10px;
    margin-top:10px;
    border-radius:5px;
    border-left-color: #1b809e;
    border-left-width: 5px;
    background-color: #f7f7f9;
}

.inva-a {
    color:inherit;
    text-decoration:none;
    font-size:18px;
}
.inva-a:hover{
    text-decoration:none;
}
{% endblock %}

{% block error %}
<something></something>
{% endblock %}

{% block content %}
    <center><h1> People </h1></center>
    {% for u in user %}
        {%if not u.is_superuser %}
        <div class="row testi">
            {%if u.profile.pic %}
                <img src="{{u.profile.pic.url}}" alt="can't display" height="50" width="50" class="img-circle" style="margin-right: 15px;" />
            {% endif %}
            <a href="{% url 'view_profile4' pk2=u.pk %}" class="inva-a">  {{u.get_full_name}} </a>
        </div>
        {% endif %}
    {% endfor %}
{% endblock %}

core/templates/testimonial.html
{% extends "header.html" %}

{% block title %}

<title>Testimonials</title>

{% endblock %}

{% block style %}

.testi {
    border:1px solid #eee;
    padding:40px;
    margin-top:10px;
    border-radius:5px;
    border-left-color: #1b809e;
    border-left-width: 5px;
    background-color: #f7f7f9;
}

{% endblock %}

{% block error %}
<something></something>
{% endblock %}

{% block content %}
    <center><h1>Testimonials</h1></center>
    <div class="row">
    {%for t in test %}
        <div class="row testi">
            <center><h2 style="color: #666;font-family:Palatino Linotype;"><i>&quot;{{t.content}}&quot;</i></h2></center><br>
            - <a href="{% url 'view_profile5' pk2=t.user.pk %}">{{t.user.get_full_name}}</a>
            <img src="{{t.user.profile.pic.url}}" alt="cannot display" height="35" width="35" class="img-circle" />
        </div>
    {% endfor %}
    </div>
{% endblock %}