alumni_support_system/urls.py
"""
Definition of urls for alumni_support_system.
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf.urls import include, url
from django.contrib.auth import views
from core import views as core_views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', alumni_support_system.views.home, name='home'),
    # url(r'^alumni_support_system/', include('alumni_support_system.alumni_support_system.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^$', core_views.home, name = 'home'),
    url(r'^login/$', views.login),
    url(r'^logout/$', views.logout, {'next_page' : '/login'}),
    url(r'^login/register/$', core_views.register_page),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^profile/$', core_views.view_profile, name = 'view_profile'),
    url(r'^profile/editprofile/$', core_views.update_profile, name='edit_profile'),
    url(r'^profile/writetestimonial/$', core_views.write_testimonial, name='write_testimonial'),
    url(r'^profile/viewtestimonial/$', core_views.view_testimonial, name='view_testimonial'),
    url(r'^profile/deletetestimonial/$', core_views.delete_testimonial, name='delete_testimonial'),
    url(r'^settings/$', core_views.settings, name='settings'), 
    url(r'^settings/changepassword/$', core_views.change_password, name='change_password'),
    url(r'^settings/deleteuser/$', core_views.delete_user, name='delete_user'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT})

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
     

core/urls.py
"""
Definition of urls for alumni_support_system.
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf.urls import include, url
from django.contrib.auth import views
from core import views as core_views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', alumni_support_system.views.home, name='home'),
    # url(r'^alumni_support_system/', include('alumni_support_system.alumni_support_system.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^$', core_views.home, name = 'home'),
    url(r'^login/$', views.login),
    url(r'^logout/$', views.logout, {'next_page' : '/login'}),
    url(r'^login/register/$', core_views.register_page),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    
    url(r'^profile/$', core_views.view_profile, name = 'view_profile'),
    url(r'^profile/editprofile/$', core_views.update_profile, name='edit_profile'),
    url(r'^profile/writetestimonial/$', core_views.write_testimonial, name='write_testimonial'),
    url(r'^profile/viewtestimonial/$', core_views.view_testimonial, name='view_testimonial'),
    url(r'^profile/deletetestimonial/$', core_views.delete_testimonial, name='delete_testimonial'),
    
    url(r'^settings/$', core_views.settings, name='settings'), 
    url(r'^settings/changepassword/$', core_views.change_password, name='change_password'),
    url(r'^settings/deleteuser/$', core_views.delete_user, name='delete_user'),
    
    url(r'^questionanswer/$', core_views.question_answer, name='question_answer_home'),
    url(r'^questionasnwer/askquestion/$', core_views.post_question, name='post_question'),
    url(r'^questionanswer/answerquestion/(?P<pk>\d+)/$', core_views.post_answer, name='post_answer'),
    url(r'^questionanswer/viewanswers/(?P<pk>\d+)/$', core_views.view_answer, name='view_answer'),
    url(r'^questionanswer/viewaskedquestions/$', core_views.view_asked_question, name='view_asked_question'),
    url(r'^questionanswer/viewaskedquestions/viewanswers/(?P<pk>\d+)/$', core_views.view_answer, name='view_answer2'),
    url(r'^questionanswer/viewansweredquestions/$', core_views.view_answered_question, name='view_answered_question'),
    url(r'^questionanswer/viewansweredquestions/viewanswers/(?P<pk>\d+)/$', core_views.view_answer, name='view_answer3'),
    url(r'^questionanswer/viewunansweredquestions/$', core_views.view_unanswered_question, name = 'view_unanswered_question'),
    url(r'^questionanswer/viewaskedquestions/deletequestion/(?P<pk2>\d+)/$', core_views.delete_question, name = 'delete_question'),
    #url(r'^questionanswer/viewanswers/(?P<pk>\d+)/deleteanswer/(?P<pk2>\d+)/$', core_views.delete_answer, name='delete_answer'),
    #url(r'^questionanswer/viewaskedquestions/viewanswers/(?P<pk>\d+)/deleteanswer/(?P<pk2>\d+)/$', core_views.delete_answer, name='delete_answer'),
    #url(r'^questionanswer/viewansweredquestions/viewanswers/(?P<pk>\d+)/deleteanswer/(?P<pk2>\d+)/$', core_views.delete_answer, name='delete_answer'),

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT})

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
     

core/models.py
import os
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import datetime,date


# Create your models here.

#NOTE : delete all users from admin before making any changes to model

#to save user dp in media/users/user_id/filename
def get_image_path(instance, filename):
    return os.path.join('users', str(instance.id), filename)

#dummy just ignore
def get_event_image_path(instance, filename):
    return os.path.join('events', str(instance.id), filename)


class Profile(models.Model):
    
    BATCH_CHOICES = (
        ('NA', 'Not Applicable'),
        ('1998','1998'),
        ('1999','1999'),
        ('2000','2000'),
        ('2001','2001'),
        ('2002','2002'),
        ('2003','2003'),
        ('2004','2004'),
        ('2005','2005'),
        ('2006','2006'),
        ('2007','2007'),
        ('2008','2008'),
        ('2009','2009'),
        ('2010','2010'),
        ('2011','2011'),
        ('2012','2012'),
        ('2013','2013'),
        ('2014','2014'),
        ('2015','2015'),
        ('2016','2016'),
        )

    
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        )

    
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    pic = models.ImageField(upload_to=get_image_path, default = os.path.join('users', 'default_avatar.jpg'))
    bio = models.TextField(max_length=500, default = '', blank=True)
    gender = models.CharField(max_length=1, choices = GENDER_CHOICES, blank = True)
    city = models.CharField(max_length=30,default = '', blank=True)
    batch = models.CharField(max_length=4, choices = BATCH_CHOICES, blank=True)
    website = models.URLField(default='', blank=True)
    twitter = models.URLField(default='', blank=True)
    linkedin = models.URLField(default='', blank=True)
    organization = models.CharField(max_length=100, default='', blank=True)

#so that profile is created and saved each time a user is created
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Testimonial(models.Model):
    user = models.OneToOneField(User, null = True, on_delete = models.CASCADE)
    content = models.TextField(max_length = 1000, default = '', blank =  True)
    pub_date = models.DateTimeField(auto_now_add = True)


class Question(models.Model):
    user = models.ForeignKey(User, null = True, on_delete = models.CASCADE)
    title = models.TextField(max_length = 200)
    description = models.TextField(max_length = 500, default = '', blank = True)
    pub_date = models.DateTimeField(auto_now_add = True)


class Answer(models.Model):
    user = models.ForeignKey(User, null = True, on_delete = models.CASCADE)
    question = models.ForeignKey(Question, null = True, on_delete = models.CASCADE)
    answer = models.TextField(max_length = 1000)
    pub_date = models.DateTimeField(auto_now_add = True)
 

class Event(models.Model):
    user = models.ForeignKey(User, null = True, on_delete = models.CASCADE)
    title = models.TextField(max_length = 50)
    date = models.DateField(default = date.today)
    time = models.TimeField(default = datetime.now)
    venue = models.TextField(max_length = 50)
    description = models.TextField(max_length = 500, blank = True, default = '')
    icon = models.ImageField(upload_to=get_image_path, default = os.path.join('users', 'default_icon.jpg'))
    pub_date = models.DateTimeField(auto_now_add = True)
 

class EventAttendees(models.Model):
    user = models.ForeignKey(User, null = True, on_delete = models.CASCADE)
    event = models.ForeignKey(Event, null = True, on_delete = models.CASCADE)


class EventGallery(models.Model):
    user = models.ForeignKey(User, null = True, on_delete = models.CASCADE)
    event = models.ForeignKey(Event, null = True, on_delete = models.CASCADE)
    pic = models.ImageField(upload_to = get_image_path, blank = True, null = True)
    pub_date = models.DateTimeField(auto_now_add = True)


class Comment(models.Model):
    user = models.ForeignKey(User, null = True, on_delete = models.CASCADE)
    event = models.ForeignKey(Event, null = True, on_delete = models.CASCADE)
    content = models.TextField(max_length = 200)
    pub_date = models.DateTimeField(auto_now_add = True)
   

core/forms.py
import re
from django.contrib.auth.models import User, Group
from core.models import Profile, Testimonial, Question, Answer, Event, EventGallery, Comment
from django.core.exceptions import ObjectDoesNotExist
from django import forms

class RegistrationForm(forms.Form):
    CHOICES = [( group.name, group.name ) for group in Group.objects.all()]
    
    username = forms.CharField(label='Username', max_length=30)
    email = forms.EmailField(label='Email')
    password1 = forms.CharField(label='Password',
                          widget=forms.PasswordInput())
    password2 = forms.CharField(label='Password (Again)',
                        widget=forms.PasswordInput())
    groupname = forms.ChoiceField(choices=CHOICES,widget = forms.widgets.RadioSelect())
    
    def clean_password2(self):
        if 'password1' in self.cleaned_data:
            password1 = self.cleaned_data['password1']
            password2 = self.cleaned_data['password2']
            if password1 == password2:
               return password2        
            raise forms.ValidationError('Passwords do not match.')
                

    def clean_username(self):
        username = self.cleaned_data['username']
        if not re.search(r'^\w+$', username):
            raise forms.ValidationError('Username can only contain alphanumeric characters and the underscore.')
        try:
            User.objects.get(username=username)
        except ObjectDoesNotExist:
            return username
        raise forms.ValidationError('Username is already taken.')


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('pic','bio','gender', 'city', 'batch', 'website','twitter','linkedin', 'organization')

class DeleteUserForm(forms.Form):
    username = forms.CharField()

class TestimonialForm(forms.ModelForm):
    class Meta:
        model = Testimonial
        fields = ('content',) 

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('title', 'description')

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ('answer',)

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ('title', 'icon', 'date', 'time', 'venue', 'description') 

class EventGalleryForm(forms.ModelForm):
    class Meta:
        model = EventGallery
        fields = ('pic',)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

class EmailForm(forms.Form):
    subject = forms.CharField(max_length=50)
    body = forms.CharField(widget = forms.Textarea())








    

core/templates/question_answer/answered_question.html
{% extends "header.html" %}
{% block style %}
h3 > span {
    padding:15px;
    margin-right:10px;
}

.que {
    border:1px solid #ccc;
    padding: 10px;
    margin-top: 10px;
    border-radius: 10px;
}

.options {
    float:right;
    position:static;
    top:0px;
}

.glyp, .glyp:hover{
    margin-left:5px;
    color:black;
}
{% endblock %}
{% block content %}

    <div class="row">
        <div class="col-md-3">
            <ul class="nav nav-pills nav-stacked">
                <li role="presentation"><a href="/questionanswer">All Questions</a></li>
                <li role="presentation"><a href="/questionanswer/askquestion">Ask Question</a></li>
                <li role="presentation"><a href="/questionanswer/viewaskedquestions">Your Questions</a></li>
                <li role="presentation" class="active"><a href="/questionanswer/viewansweredquestions">View Answered Questions</a></li>
                <li role="presentation"><a href="/questionanswer/viewunansweredquestions">Answer Questions</a></li>
            </ul>
        </div>
        <div class="col-md-9">
            <h3> Your Questions : </h3>
            {% for q in ques%}
                <div class="row que">               
                    <h3><span class="label label-primary"> Question </span> {{q.title}}</h3><br>
                    {{q.description}}
                    <span style="float: right;">Asked by <strong>{{q.user}}</strong> @ <em>{{q.pub_date}}</em></span>
                    <div class="options" style="float: right;clear: both;">
                        <a href="{% url 'view_answer3' pk=q.pk %}" class="glyphicon glyphicon-menu-hamburger glyp"></a>
                    </div>
                </div>
                        
                  
            {% endfor %}
        </div>
    </div>
{% endblock %}

core/templates/question_answer/asked_question.html
{% extends "header.html" %}
{% block style %}
h3 > span {
    padding:15px;
    margin-right:10px;
}

.que {
    border:1px solid #ccc;
    padding: 10px;
    margin-top: 10px;
    border-radius: 10px;
}

.options {
    float:right;
    position:static;
    top:0px;
}

.glyp, .glyp:hover{
    margin-left:5px;
    color:black;
}
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-md-3">
            <ul class="nav nav-pills nav-stacked">
                <li role="presentation"><a href="/questionanswer">All Questions</a></li>
                <li role="presentation"><a href="/questionanswer/askquestion">Ask Question</a></li>
                <li role="presentation" class="active"><a href="/questionanswer/viewaskedquestions">Your Questions</a></li>
                <li role="presentation"><a href="/questionanswer/viewansweredquestions">View Answered Questions</a></li>
                <li role="presentation"><a href="/questionanswer/viewunansweredquestions">Answer Questions</a></li>
            </ul>
        </div>
        <div class="col-md-9">
            <h3> Your Questions : </h3>
            {% for q in ques%}
                <div class="row que">
                    <h3><span class="label label-primary"> Question </span> {{q.title}}</h3><br>
                    
                    {{q.description}}
                    <span style="float: right;">Asked by <strong>{{q.user}}</strong> @ <em>{{q.pub_date}}</em></span>
                    <div class="options">
                        <a href="{% url 'delete_question' pk2=q.pk %}" class="glyphicon glyphicon-trash glyp" ></a>
                        <a href="{% url 'view_answer2' pk=q.pk %}" class="glyphicon glyphicon-menu-hamburger glyp"></a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

<!-- extra fields : user , pub_date-->

core/templates/question_answer/post_answer.html
{% extends "header.html" %}

{% block title %}
<title>Answer Question | {{ques.title}}</title>
{% endblock %}

{% block style %}
label {
    width: 0.1px;
    height: 0.1px;
    opacity: 0;
    overflow: hidden;
    position: absolute;
    z-index: -1;
}


#id_answer {
    margin-top:10px;
    width:100%;
    height:100px;
    border:1px solid #ccc;
    border-radius:4px;
    resize:none;
}

.testi {
    border:1px solid #eee;
    padding:10px;
    margin-top:10px;
    border-radius:5px;
    border-left-color: #1b809e;
    border-left-width: 5px;
    background-color: #f7f7f9;
}
{% endblock %}

{% block content %}
   
    <div class="row">
        <div class="col-md-3">
            <ul class="nav nav-pills nav-stacked">
                <li role="presentation"><a href="/questionanswer">All Questions</a></li>
                <li role="presentation"><a href="/questionanswer/askquestion">Ask Question</a></li>
                <li role="presentation"><a href="/questionanswer/viewaskedquestions">Your Questions</a></li>
                <li role="presentation"><a href="/questionanswer/viewansweredquestions">View Answered Questions</a></li>
                <li role="presentation" class="active"><a href="/questionanswer/viewunansweredquestions">Answer Questions</a></li>
            </ul>
        </div>
        <div class="col-md-8 center-block">
        <center>
        <div class="testi">
            <h2>{{ques.title}}</h2>
            <h3>{{ques.description}}</h3>
            <span style="float: right;">Asked by <strong>{{ques.user}}</strong> @ <em>{{ques.pub_date}}</em></span>
        </div>
            <form method="post" action="">
                {%csrf_token%}
                {{answer_form.as_p}}
                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </center>
        </div>
    </div>
    
{% endblock %}

core/templates/question_answer/post_question.html
{% extends "header.html" %}

{% block style %}
textarea {
    resize:none;
    width:500px;
    height: 100px;
    border-radius:10px;
}
#poster {
    width:200px;
}
.labell {
    font-size:20;
    padding:10px;    
    border-radius:10px;
    background-color:#6699ff;
    color:white;
}
{% endblock %}
{% block content %}

    <div class="row">
        <div class="col-md-3">
            <ul class="nav nav-pills nav-stacked">
                <li role="presentation"><a href="/questionanswer">All Questions</a></li>
                <li role="presentation" class="active"><a href="/questionanswer/askquestion">Ask Question</a></li>
                <li role="presentation"><a href="/questionanswer/viewaskedquestions">Your Questions</a></li>
                <li role="presentation"><a href="/questionanswer/viewansweredquestions">View Answered Questions</a></li>
                <li role="presentation"><a href="/questionanswer/viewunansweredquestions">Answer Questions</a></li>
            </ul>
        </div>
        <div class="col-md-9">
    <h3> Post your question</h3><br>
    <form method="post" action="">
        {%csrf_token%}
        <div class="row">
            <span class="labell">Question</span><br>
            {{question_form.title}}
        </div><br>
        <div class="row">
            <span class="labell">Description</span><br>
            {{question_form.description}}
        </div>
        <button class="btn btn-primary btn-lg btn-block" id="poster" type="submit">Post</button>
    </form>
        </div>
    </div>
{% endblock %}

<!-- form fields : title, description -->

core/templates/question_answer/question_home.html
{% extends "header.html" %}

{% block style %}
h3 > span {
    padding:15px;
    margin-right:10px;
}

.que {
    border:1px solid #ccc;
    padding: 10px;
    margin-top: 10px;
    border-radius: 10px;
}

.options {
    float:right;
    position:static;
    top:0px;
}

.glyp, .glyp:hover{
    margin-left:5px;
    color:black;
}
{% endblock %}

{% block content %}
    
    <div class="row">
        <div class="col-md-3">
            <ul class="nav nav-pills nav-stacked">
                <li role="presentation" class="active"><a href="/questionanswer">All Questions</a></li>
                <li role="presentation"><a href="/questionanswer/askquestion">Ask Question</a></li>
                <li role="presentation"><a href="/questionanswer/viewaskedquestions">Your Questions</a></li>
                <li role="presentation"><a href="/questionanswer/viewansweredquestions">View Answered Questions</a></li>
                <li role="presentation"><a href="/questionanswer/viewunansweredquestions">Answer Questions</a></li>
            </ul>
                    </div>
        <div class="col-md-9">
    <h3> Questions : </h3>
    {% for q in ques %}
        <div class="row que">
            <h3><span class="label label-primary"> Question </span> {{q.title}}</h3><br>
            <p>{{q.description}}</p>
            <span style="float: right;">Asked by <strong>{{q.user}}</strong> @ <em>{{q.pub_date}}</em></span>
            <div class="options">
                <a href="{% url 'post_answer' pk=q.pk %}"  class="glyphicon glyphicon-pencil glyp"></a>
                <a href="{% url 'view_answer' pk=q.pk %}" class="glyphicon glyphicon-menu-hamburger glyp"></a>
            </div>
        </div>
    {% endfor %}
        </div>
    </div>
{% endblock %}
<!-- extra fields : user , pub_date-->

core/templates/question_answer/unanswered_question.html
{% extends "header.html" %}

{% block style %}
h3 > span {
    padding:15px;
    margin-right:10px;
}

.que {
    border:1px solid #ccc;
    padding: 10px;
    margin-top: 10px;
    border-radius: 6px;
}

.options {
    float:right;
    position:static;
    top:0px;
}

.glyp, .glyp:hover{
    margin-left:5px;
    color:black;
}
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-md-3">
            <ul class="nav nav-pills nav-stacked">
                <li role="presentation"><a href="/questionanswer">All Questions</a></li>
                <li role="presentation"><a href="/questionanswer/askquestion">Ask Question</a></li>
                <li role="presentation"><a href="/questionanswer/viewaskedquestions">Your Questions</a></li>
                <li role="presentation"><a href="/questionanswer/viewansweredquestions">View Answered Questions</a></li>
                <li role="presentation" class="active"><a href="/questionanswer/viewunansweredquestions">Answer Questions</a></li>
            </ul>
        </div>
    <div class="col-md-9">
    <h3> New Questions : </h3>
    {% for q in ques %}
        <div class="row que">                    
            
            <h3><span class="label label-primary"> Question </span> {{q.title}}</h3><br>
            <span class="description">{{q.description}}</span> 
            <span style="float: right;">Asked by <strong>{{q.user}}</strong> @ <em>{{q.pub_date}}</em></span>
            <div class="options">
                <a href="{% url 'post_answer' pk=q.pk %}" class="glyphicon glyphicon-pencil glyp"></a>
            </div>               
        </div>
    {% endfor %}
    </div>
{% endblock %}

<!-- extra fields : user , pub_date-->

core/templates/question_answer/view_answer.html
{% extends "header.html" %}

{% block style %}
h3 > span {
    padding:15px;
    margin-right:10px;
}

.que {
    border:1px solid #ccc;
    padding: 10px;
    margin-top: 10px;
    border-radius: 10px;
}

.options {
    float:right;
    position:static;
    top:0px;
}

.glyp, .glyp:hover{
    margin-left:5px;
    color:black;
}

.testi {
    border:1px solid #eee;
    padding:10px;
    margin-top:10px;
    border-radius:5px;
    border-left-color: #1b809e;
    border-left-width: 5px;
}
{% endblock %}

{% block content %}    

    <div class="row">
        <div class="col-md-3">
            <ul class="nav nav-pills nav-stacked">
                <li role="presentation"><a href="/questionanswer">All Questions</a></li>
                <li role="presentation"><a href="/questionanswer/askquestion">Ask Question</a></li>
                <li role="presentation"><a href="/questionanswer/viewaskedquestions">Your Questions</a></li>
                <li role="presentation"><a href="/questionanswer/viewansweredquestions">View Answered Questions</a></li>
                <li role="presentation"><a href="/questionanswer/viewunansweredquestions">Answer Questions</a></li>
            </ul>
        </div>
        <div class="col-md-9">
            <div class="row que">
                <h3><span class="label label-primary"> Question </span> {{ques.title}}</h3>
                <p style="font-size: 20px;font-family:Palatino Linotype;font-color:#888"> {{ques.description}}</p>
                <span style="float: right;">Asked by <strong>{{ques.user}}</strong> @ <em>{{ques.pub_date}}</em></span>                
            </div>
            <h3 style="padding-left: 40px;">Answers</h3>
            {% for a in ans %}
                <div class="row testi">
                    <strong>{{a.user.get_full_name}}</strong> : <em>{{a.answer}}</em>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

<!-- extra fields : user , pub_date-->